[solution]
name = "dogacel-solution-v1"        # Solution name
definition = "dsa_sparse_attention_h16_ckv512_kpe64_topk2048_ps64"     # Track: fused_moe | sparse_attention | gated_delta_net
author = "Doğaç Eldenk"             # Team/author name

[build]
language = "triton"                 # triton | cuda (cutedsl uses triton builder)
source_dir = "triton"               # Source directory under solution/
entry_point = "fused.py::kernel"    # Kernel function name
